name: Build macOS Terminal App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        working-directory: mac
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests gitpython

      - name: Build Terminal App
        working-directory: mac
        run: python setup.py

      - name: Create macOS Installer (.pkg)
        run: |
          mkdir -p payload/usr/local/bin
          mv mac/dist/gitFlow payload/usr/local/bin/
          pkgbuild --root payload --identifier com.yourdomain.gitFlow --version 1.0 --install-location /usr/local/bin mac/gitFlow.pkg

      - name: Install create-dmg (for .dmg creation)
        run: brew install create-dmg

      - name: Create macOS Disk Image (.dmg)
        run: |
          create-dmg --app=mac/dist/gitFlow --dmg=mac/gitFlow.dmg

      - name: Upload .pkg Installer
        uses: actions/upload-artifact@v4
        with:
          name: gitFlow-mac-installer
          path: mac/gitFlow.pkg

      - name: Upload .dmg Installer
        uses: actions/upload-artifact@v4
        with:
          name: gitFlow-mac-dmg
          path: mac/gitFlow.dmg
